#!/usr/bin/gawk -f

BEGIN {
  bck = 0
  empty_bck = 0
}

/^msgid/ {
  bck++
}

/^msgid[ \t]*""/ {
  empty_bck++
}

/^"Language: \w/ {
  gsub(/^"Language: *|\\n"/,"")
  languages[l++] = $0
}

/^# */ && /<.*@.*>/ && !/^"Report/ && !/FIRST/ && !/^"Language/{
  gsub(/^[^ ]*[ "]*|<.*$/,"")

  b=0
  for (k in authors){
    if(authors[k]==$0){
      b=1
      break
    }
  }
  if(b==0){
    authors[i++]=$0
  }

}

END {
  print("Quantidade de blocos: " bck)
  print("Percentagem de blocos com traducao: " (bck - empty_bck)*100/bck "%")
  print("Ha " i " tradutores, eles sao:")

  # temos de ver os po's em FR, ta muito mal os autores la
  for (j in authors){
    print( "\t" authors[j])
  }

  print("Ha " l " linguagens, elas sao:")
  for(j in languages){print("\t" languages[j])}



}
