#!/usr/bin/gawk -f

BEGIN {
	FS = "\""
}

/^"Language-Team:/ {
  gsub(/^"Language-Team: *| *<.*/,"")
  language = tolower($0)
  if(language=="brazilian portugueses"){
  	language="brazilian portuguese"
  }
}

/^msgid[ \t]*""/ {
  next
}

/^msgstr[ \t]*""/ {
  next
}

/^msgid *"/ {
  msg = $2
}

/^msgstr *"/ {
  dic[msg][language] = $2
}

END{

	#i-> msg ; j  -> lang
	for ( i in dic){
		if(length(dic[i]) == 2){
			print(dic[i]["brazilian portuguese"] " -> " dic[i]["français"])
		}	
	}
}












