#!/usr/bin/gawk -f

BEGIN {
	FS = "\""
}

/^"Language:/ {
  gsub(/^"Language: *|\\n"/,"")
  language = $0
}

/^msgid[ \t]*""/ {
  next
}

/^msgstr[ \t]*""/ {
  next
}

/^msgid *"/ {
  msg = $2
}

/^msgstr *"/ {
  dic[language][msg] = $2
}

END{
	for ( i in dic){
		for ( j in dic[i] ){
			print( dic[i] "->" dic[i][j])
		}
	}
}