#!/usr/bin/gawk -f

BEGIN {
	FS = "\""

	print("PT\t->\tFR")


}

/^"Language-Team: *\\n"/{
  next
}

/^"Language-Team:/ {
  gsub(/^"Language-Team: *| *<.*/,"")
  language = tolower($0)
  if(language ~ /portugu[êe]se?s?/){
  	language = "PT"
  }else{
		language = "FR"
	}

}

/^msgid[ \t]*""/ {
  next
}

/^msgstr[ \t]*""/ {
  next
}

/^msgid *"/ {
  msg = $2
}

/^msgstr *"/ {
  dic[msg][language] = $2
}

END{

	for ( i in dic){
		if(length(dic[i]) == 2){
			print(dic[i]["PT"] " -> " dic[i]["FR"])
		}
	}
}
